<a href="https://colab.research.google.com/github/Seenuprime/Certificates/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'cleaned_df.csv')
df

,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
0,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5
...,...,...,...,...,...,...
1047311,M,NEW DELHI,7635.19,18/9/16,184824,799.0
1047312,M,NASHIK,27311.42,18/9/16,183734,460.0
1047313,M,HYDERABAD,221757.06,18/9/16,183313,770.0
1047314,M,VISAKHAPATNAM,10117.87,18/9/16,184706,1000.0
1047315,M,PUNE,75734.42,18/9/16,181222,1166.0

In [48]:
df.drop(columns=['TransactionDate', 'TransactionTime'], axis=1, inplace=True)

In [3]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['CustGender'] = encoder.fit_transform(df['CustGender'])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.iloc[:, [2, 5]] = scaler.fit_transform(df.iloc[:, [2, 5]])

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[
        ('encode', CountVectorizer(), 'CustLocation')
    ],
    remainder='passthrough'
)

In [46]:
transformed_data = ct.fit_transform(df)

ValueError: For a sparse output, all columns should be a numeric or convertible to a numeric.

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1047316 entries, 0 to 1047315
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   CustGender               1047316 non-null  int64
 1   CustLocation             1047316 non-null  object
 2   CustAccountBalance       1047316 non-null  float64
 3   TransactionDate          1047316 non-null  object
 4   TransactionTime          1047316 non-null  int64
 5   TransactionAmount (INR)  1047316 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 47.9+ MB